{-# LANGUAGE OverloadedStrings #-}
-- |
-- Module      : Cospan
-- Description : H(Arg) horizontal 1-cells as cospans in Set^A
--
-- = Theoretical context
--
-- The paper (Definition 2.1, §2 of Afanador 2025) establishes the category
-- of argumentation frameworks AArg as a weakly double category whose
-- horizontal 1-cells are cospans in Set^A.  A cospan
--
--     A --[leftLeg]--> R <--[rightLeg]-- B
--
-- encodes a *dialogical interaction*: the apex R is the shared relational
-- space into which argument sets A and B both map.  Arguments that are
-- injected to the same element of R are identified — they are the "same
-- argument" from the perspective of the interaction.
--
-- Horizontal composition of cospans
--
--     (A -> R <- B)  ;  (B -> S <- C)
--
-- is the pushout of the span R <-[f_b]- B -[g_b]-> S.  The pushout apex
-- T = R +_B S is the coproduct of R and S quotiented by the equivalence
-- generated by f_b(b) ~ g_b(b) for every b : B.  This produces the
-- composite cospan A -> T <- C.
--
-- In sets (the category relevant for Year 1 concrete types), the pushout of
-- two sets glued along a common subset is the disjoint union quotiented by
-- that identification — concretely representable as 'Either r s' quotiented
-- by the relation {(Left (f b), Right (g b)) | b : B}.
--
-- The horizontal bicategory H(AArg) has:
--   Objects: argument sets (concretely, 'Set Text' / domain of 'WArgArgs')
--   1-cells: cospans of argument sets
--   2-cells: cospan morphisms — triples (f_a, phi, f_b) where phi: R -> S is
--            an isomorphism making the cospan squares commute (paper §2).
--
-- = Relationship to structured/decorated cospans (Todo 4 context)
--
-- The paper Corollary following Proposition 1 identifies WArg with the
-- category of W-structured cospans _W Csp(Arg) where W: Arg -> D is the
-- weighting functor.  The coend/optic formulation of Prism (§3) will require
-- this structured-cospan perspective.  For Year 1 we only need the plain
-- cospan structure; the W-decoration and its coherence with the actegory
-- action are deferred to Todo 4 / Year 2 Agda.
--
-- = What is deferred
--
-- * The pushout typeclass has a concrete 'Either'-based instance for the
--   Map Text setting.  The universal property (that any cospan through a
--   common mediation factors uniquely through the pushout) is stated as a
--   comment obligation but is not QuickCheck-verified at Year 1 — verifying
--   the universal property requires quantifying over all mediating maps, which
--   demands either a Yoneda argument or an Agda proof.
-- * 2-cells (cospan morphisms) are not represented; they become the
--   reparametrisations in Para in Todo 4.
-- * The full double-category structure (vertical composition, interchange)
--   is deferred to Year 2 Agda.
--
-- See: Afanador (2025), ACT 2025 paper, Definition 2.1 and surrounding text.
-- See: Weisbart et al. (2023), "Constructing" (ref [compositionality:13517]).
module Cospan
  ( Cospan(..)
  , PushoutApex(..)
  , composeCospan
    -- * Concrete Map Text instance
  , MapPushout(..)
  , pushoutMaps
    -- * QuickCheck properties
  , prop_cospan_leftleg_total
  , prop_cospan_rightleg_total
  , prop_pushout_left_commutes
  , prop_pushout_right_commutes
  ) where

import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Text (Text)
import Test.QuickCheck ()

-- ---------------------------------------------------------------------------
-- Core cospan type
-- ---------------------------------------------------------------------------

-- | A cospan from 'a' to 'b' with apex 'r'.
--
-- In H(AArg):
--   a, b  — sets of argument identifiers (objects of Set^A)
--   r     — the shared relational apex (the "arena" of interaction)
--   leftLeg  :: a -> r   — injection of left-hand arguments into the arena
--   rightLeg :: b -> r   — injection of right-hand arguments into the arena
--
-- Both legs must be total functions.  In the Set^A setting they are
-- typically injective (no two distinct arguments are identified unless
-- they are the "same" argument in the interaction), but injectivity is not
-- required by the definition.
--
-- This type is parametric in all three sets for maximum generality.  In the
-- concrete Map Text-based setting, 'a', 'b', and 'r' will all be 'Text'
-- (argument identifiers).
data Cospan a r b = Cospan
  { leftLeg  :: a -> r
    -- ^ Injection of the left argument set into the interaction apex.
  , rightLeg :: b -> r
    -- ^ Injection of the right argument set into the interaction apex.
  }

-- ---------------------------------------------------------------------------
-- Pushout
-- ---------------------------------------------------------------------------

-- | The pushout apex of a span  r <-[f]- b -[g]-> s.
--
-- In Set, the pushout is the disjoint union (r + s) quotiented by the
-- smallest equivalence relation ~ satisfying: f(b) ~ g(b) for all b : B.
--
-- We represent this concretely as 'Either r s' (the raw disjoint union)
-- paired with the identification map.  For the Map Text case the "quotient"
-- is implemented by a canonical renaming: elements of 'r' in the image of
-- 'f' and elements of 's' in the image of 'g' are mapped to the same
-- representative Text key.
--
-- Year 1 limitation: we do not verify the universal property (uniqueness of
-- mediating maps).  That is a Year 2 Agda obligation.
data PushoutApex r s = PushoutApex
  { pushLeft  :: r -> Text
    -- ^ Inject 'r' into the pushout apex (canonical Text key).
  , pushRight :: s -> Text
    -- ^ Inject 's' into the pushout apex (canonical Text key).
  }

-- | The result of computing a Map Text pushout.
--
-- For two maps over Text keys glued along a shared set of keys 'b',
-- the pushout apex is:
--   * All keys of 'r' prefixed with "L:" if they are NOT in the image of the
--     gluing, or with their canonical name if they ARE in the image.
--   * All keys of 's' prefixed with "R:" if they are NOT in the image of the
--     gluing.
--   * Shared keys (those in both images) get a single representative (the
--     'r' version, by convention).
--
-- This is the concretisation of the set-theoretic pushout for the WArg case
-- where argument identifiers are Text keys.
data MapPushout = MapPushout
  { mpLeft  :: Text -> Text
    -- ^ leftLeg: keys of the first apex map to pushout keys.
  , mpRight :: Text -> Text
    -- ^ rightLeg: keys of the second apex map to pushout keys.
  }

-- | Compute the pushout of two argument-set maps glued along a shared domain.
--
-- Given:
--   f :: Text -> Text  (left  leg of the span: shared set B -> R)
--   g :: Text -> Text  (right leg of the span: shared set B -> S)
--   sharedKeys :: [Text]  (the shared set B)
--
-- Produces a 'MapPushout' whose 'mpLeft' and 'mpRight' are the canonical
-- pushout injections.  The pushout commutation law:
--
--     mpLeft po . f b == mpRight po . g b  (for all b in sharedKeys)
--
-- is satisfied by construction: shared keys are mapped to their 'r'-side
-- canonical name (no "L:" prefix), and their 's'-side image is mapped to
-- the same name via 'g'.
--
-- Non-shared keys in R receive the "L:" prefix; non-shared keys in S
-- receive the "R:" prefix.  This ensures injectivity of each leg.
pushoutMaps :: (Text -> Text)  -- ^ f: B -> R (left span leg)
            -> (Text -> Text)  -- ^ g: B -> S (right span leg)
            -> [Text]          -- ^ B: shared keys
            -> MapPushout
pushoutMaps f g sharedKeys = MapPushout
  { mpLeft  = \r ->
      -- r is already a canonical key in R.
      -- If r is in the image of f (i.e., r = f b for some shared b),
      -- use the canonical representative directly.
      -- Otherwise prefix with "L:".
      if r `elem` sharedImages
        then r
        else "L:" <> r
  , mpRight = \s ->
      -- s is a key in S.
      -- If s = g b for some shared b, it must be identified with f b.
      -- Otherwise prefix with "R:".
      case Map.lookup s gInverse of
        Just b  -> f b   -- identified with the R-side image of f
        Nothing -> "R:" <> s
  }
  where
    -- The image of f over shared keys: these R-elements are "occupied"
    sharedImages :: [Text]
    sharedImages = map f sharedKeys

    -- Inverse of g restricted to shared keys: g(b) -> b
    gInverse :: Map Text Text
    gInverse = Map.fromList [(g b, b) | b <- sharedKeys]

-- ---------------------------------------------------------------------------
-- Horizontal composition of cospans
-- ---------------------------------------------------------------------------

-- | Horizontal composition of two cospans via a pushout.
--
-- Given:
--   cs1 : A -> R <- B  (a cospan from A to B)
--   cs2 : B -> S <- C  (a cospan from B to C)
--   f   : B -> R       (= rightLeg cs1, the right leg of cs1, also left span leg)
--   g   : B -> S       (= leftLeg  cs2, the left  leg of cs2, also right span leg)
--   po  : MapPushout   (the pushout of R <-[f]- B -[g]-> S)
--
-- Produces: A -> T <- C  where T = pushout apex.
--
-- The composed left  leg is: mpLeft po . leftLeg  cs1 :: A -> Text
-- The composed right leg is: mpRight po . rightLeg cs2 :: C -> Text
--
-- The inner B is "absorbed" into the pushout; it no longer appears in the
-- composite cospan type.
--
-- Note: 'f' and 'g' are passed separately to allow the caller to supply the
-- specific gluing maps (they should equal rightLeg cs1 and leftLeg cs2
-- respectively, but the type system cannot enforce this at Year 1 without
-- dependent types — this is a Year 2 Agda obligation).
composeCospan
  :: MapPushout
  -> Cospan a Text b   -- ^ cs1 : A -> R <- B (R concretised as Text)
  -> Cospan b Text c   -- ^ cs2 : B -> S <- C (S concretised as Text)
  -> Cospan a Text c   -- ^ composite: A -> T <- C
composeCospan po cs1 cs2 = Cospan
  { leftLeg  = mpLeft  po . leftLeg  cs1
  , rightLeg = mpRight po . rightLeg cs2
  }

-- ---------------------------------------------------------------------------
-- QuickCheck properties
-- ---------------------------------------------------------------------------

-- | A 'Cospan Text Text Text' with the identity as both legs.
-- This is the "trivial" cospan — both argument sets are already in the
-- same space; it serves as a unit test object.
identityCospan :: Cospan Text Text Text
identityCospan = Cospan id id

-- | Totality sanity: leftLeg of the identity cospan returns its argument.
--
-- This trivially verifies that 'leftLeg identityCospan x == x' for all x.
-- It is a smoke test confirming the cospan data type is well-formed, not
-- a mathematical law.
prop_cospan_leftleg_total :: Text -> Bool
prop_cospan_leftleg_total x = leftLeg identityCospan x == x

-- | Totality sanity: rightLeg of the identity cospan returns its argument.
prop_cospan_rightleg_total :: Text -> Bool
prop_cospan_rightleg_total x = rightLeg identityCospan x == x

-- | Pushout commutation law (left triangle):
-- mpLeft po . f b == mpRight po . g b  for all shared b.
--
-- This is the fundamental property that makes 'pushoutMaps' a genuine pushout:
-- shared keys are identified by both injections.
--
-- We test it for the concrete case where f = id (B = R, the shared set is
-- already embedded as identity in R) and g = id (B = S).
-- In this degenerate case, sharedKeys = the domain of both maps, and the
-- pushout should identify everything (the apex collapses to B itself modulo
-- the "L:" tagging).
prop_pushout_left_commutes :: [Text] -> Bool
prop_pushout_left_commutes bs =
  all (\b -> mpLeft po (f b) == mpRight po (g b)) bs
  where
    f = id  -- left span leg: B -> R = identity
    g = id  -- right span leg: B -> S = identity
    po = pushoutMaps f g bs

-- | Pushout commutation law (right triangle), with a nontrivial renaming.
--
-- We use f b = "F:" <> b and g b = "G:" <> b.  For each shared b,
-- mpLeft po . f b should equal mpRight po . g b.
prop_pushout_right_commutes :: [Text] -> Bool
prop_pushout_right_commutes bs =
  all (\b -> mpLeft po (f b) == mpRight po (g b)) bs
  where
    f b = "F:" <> b
    g b = "G:" <> b
    po = pushoutMaps f g bs
