-- |
-- Module      : DUnit
-- Description : D-Poset on the unit interval [0,1]
--
-- A D-Poset (difference poset) is a bounded partially ordered set (P, ≤, 0)
-- equipped with a partial subtraction b \\ a defined when a ≤ b, satisfying:
-- (i)  b \\ a ≤ b
-- (ii) b \\ (b \\ a) = a  (involution law)
-- (iii) if a ≤ b ≤ c then c \\ b ≤ c \\ a and (c \\ a) \\ (c \\ b) = b \\ a
--
-- The unit interval [0,1] carries the canonical D-Poset structure where
-- b \\ a = b − a when a ≤ b. This is the concrete mathematical substrate
-- over which the h-categoriser fixed-point operates (Stratum A, Year 0).
-- The D-Poset typing is not decorative: it is what makes the gradual
-- semantics structurally correct as an action on (D-Posets, ⊗, j).
--
-- See: Jacobs & Mandemaker (2012), "Coreflections in algebraic quantum logic",
-- Foundations of Physics 42, 932–958. [13]
module DUnit
  ( DUnit(..)
  , mkDUnit
  , dDiff
  , prop_diff_antitone
  , prop_diff_involution
  ) where

import Data.Maybe (fromMaybe)
import GHC.Generics (Generic)
import Test.QuickCheck

-- | The unit interval as a D-Poset. Gradual semantics live here.
--
-- Invariant: 0 ≤ unDUnit d ≤ 1. Enforced by the smart constructor 'mkDUnit';
-- the raw constructor is exported for deserialization but callers should
-- prefer 'mkDUnit'.
newtype DUnit = DUnit { unDUnit :: Double }
  deriving (Eq, Ord, Show, Generic)

-- | Smart constructor: clamp to [0,1].
mkDUnit :: Double -> DUnit
mkDUnit = DUnit . max 0.0 . min 1.0

-- | Partial subtraction: b \\ a, defined when a ≤ b.
--
-- We use a small tolerance (1e-12) to absorb floating-point rounding in
-- the ≤ comparison. The result is clamped to 0 to avoid negative values
-- from the same rounding.
dDiff :: DUnit -> DUnit -> Maybe DUnit
dDiff (DUnit b) (DUnit a)
  | a <= b + 1e-12 = Just (DUnit (max 0.0 (b - a)))
  | otherwise      = Nothing

-- ---------------------------------------------------------------------------
-- Arbitrary instance
-- ---------------------------------------------------------------------------

instance Arbitrary DUnit where
  arbitrary = DUnit . min 1.0 . abs <$> (arbitrary :: Gen Double)
  shrink (DUnit x) = [DUnit x' | x' <- shrink x, x' >= 0.0, x' <= 1.0]

-- ---------------------------------------------------------------------------
-- QuickCheck D-Poset laws
-- ---------------------------------------------------------------------------

-- | D-Poset law (iii), antitone part:
-- if a ≤ b ≤ c then c \\ b ≤ c \\ a.
--
-- The triple (a, b, c) is generated by construction so the ordering
-- invariant a ≤ b ≤ c holds structurally.  We generate a uniformly in
-- [0,1], then add small non-negative deltas to obtain b and c, clamping
-- to 1.0.  This eliminates the ==> guard and the associated discarding of
-- test cases that made the previous version nearly vacuous with uniform
-- independent draws.
--
-- fromMaybe True remains correct: given a ≤ b ≤ c the partial subtraction
-- dDiff c b and dDiff c a are both defined, so Nothing is unreachable here;
-- the fallback is a conservative pass for any residual floating-point edge
-- cases at the boundary.
prop_diff_antitone :: Property
prop_diff_antitone = forAll gen $ \(a, b, c) ->
    fromMaybe True $ do
      cminb <- dDiff c b
      cmina <- dDiff c a
      return (cminb <= cmina)
  where
    gen :: Gen (DUnit, DUnit, DUnit)
    gen = do
      a      <- arbitrary :: Gen DUnit
      delta1 <- abs <$> (arbitrary :: Gen Double)
      delta2 <- abs <$> (arbitrary :: Gen Double)
      let b = DUnit (min 1.0 (unDUnit a + delta1))
          c = DUnit (min 1.0 (unDUnit b + delta2))
      return (a, b, c)

-- | D-Poset law (ii): b \\ (b \\ a) = a  (involution up to tolerance 1e-10).
--
-- When a > b the partial subtraction is undefined and the property does
-- not apply; we fail with fromMaybe False to make the vacuous case visible
-- in QuickCheck statistics.
prop_diff_involution :: DUnit -> DUnit -> Property
prop_diff_involution a b =
  a <= b ==>
    fromMaybe False $ do
      bma  <- dDiff b a
      back <- dDiff b bma
      return (abs (unDUnit back - unDUnit a) < 1e-10)
