-- |
-- Module      : DUnit
-- Description : D-Poset on the unit interval [0,1]
--
-- A D-Poset (difference poset) is a bounded partially ordered set (P, ≤, 0)
-- equipped with a partial subtraction b \\ a defined when a ≤ b, satisfying:
-- (i)  b \\ a ≤ b
-- (ii) b \\ (b \\ a) = a  (involution law)
-- (iii) if a ≤ b ≤ c then c \\ b ≤ c \\ a and (c \\ a) \\ (c \\ b) = b \\ a
--
-- The unit interval [0,1] carries the canonical D-Poset structure where
-- b \\ a = b − a when a ≤ b. This is the concrete mathematical substrate
-- over which the h-categoriser fixed-point operates (Stratum A, Year 0).
-- The D-Poset typing is not decorative: it is what makes the gradual
-- semantics structurally correct as an action on (D-Posets, ⊗, j).
--
-- See: Jacobs & Mandemaker (2012), "Coreflections in algebraic quantum logic",
-- Foundations of Physics 42, 932–958. [13]
module DUnit
  ( DUnit(..)
  , mkDUnit
  , dDiff
  , prop_diff_exists
  , prop_diff_upper_bound
  , prop_diff_antitone
  , prop_diff_involution
  ) where

import Data.Maybe (fromMaybe)
import Data.Ratio ((%))
import GHC.Generics (Generic)
import Test.QuickCheck

-- | The unit interval as a D-Poset. Gradual semantics live here.
--
-- Invariant: 0 ≤ unDUnit d ≤ 1. Enforced by the smart constructor 'mkDUnit';
-- the raw constructor is exported for deserialization but callers should
-- prefer 'mkDUnit'.
--
-- The underlying type is 'Rational' (i.e. GHC.Real.Ratio Integer) rather than
-- Double. Rational arithmetic is exact, so the D-Poset laws hold without any
-- ε-tolerance: b \\ (b \\ a) = a is definitionally true because Rational
-- subtraction is a ring operation, not an IEEE-754 approximation.
-- (Flaw 2 of architecture_flaws.md resolved.)
newtype DUnit = DUnit { unDUnit :: Rational }
  deriving (Eq, Ord, Generic)

-- | Show as a decimal fraction for readability (e.g. "3 % 4").
instance Show DUnit where
  show (DUnit r) = "DUnit (" ++ show r ++ ")"

-- | Smart constructor: clamp to [0,1] using exact Rational comparisons.
mkDUnit :: Rational -> DUnit
mkDUnit = DUnit . max 0 . min 1

-- | Partial subtraction: b \\ a, defined when a ≤ b.
--
-- Rational subtraction is exact: no ε guard is required or appropriate.
-- If a ≤ b then b - a is a well-defined non-negative Rational. The old
-- 1e-12 tolerance was a symptom of IEEE-754 imprecision; it is gone.
dDiff :: DUnit -> DUnit -> Maybe DUnit
dDiff (DUnit b) (DUnit a)
  | a <= b    = Just (DUnit (b - a))
  | otherwise = Nothing

-- ---------------------------------------------------------------------------
-- Arbitrary instance
-- ---------------------------------------------------------------------------

-- | Generate DUnit values as exact rationals n/1000 for n ∈ {0,...,1000}.
--
-- This gives 1001 evenly-spaced exact values in [0,1] with no floating-point
-- contamination. Shrinking reduces the numerator toward 0.
instance Arbitrary DUnit where
  arbitrary = do
    n <- chooseInt (0, 1000)
    return (DUnit (fromIntegral n % 1000))
  shrink (DUnit r) =
    [ DUnit r'
    | r' <- shrink r
    , r' >= 0
    , r' <= 1
    ]

-- ---------------------------------------------------------------------------
-- QuickCheck D-Poset laws
-- ---------------------------------------------------------------------------

-- | D-Poset law existence: if a ≤ b then dDiff b a is defined (not Nothing).
--
-- This is law (i) in its partiality aspect: the subtraction b \ a exists
-- whenever a ≤ b. Trivially satisfied by the formula (b − a is defined for
-- all reals), but testing it explicitly catches any future changes to the
-- guard in 'dDiff' that would incorrectly reject the defined case.
--
-- The ==> guard discards cases where a > b; in those cases dDiff b a is
-- correctly Nothing and the property does not apply.
prop_diff_exists :: DUnit -> DUnit -> Property
prop_diff_exists a b =
  a <= b ==>
    case dDiff b a of
      Nothing -> False
      Just _  -> True

-- | D-Poset law (i), upper bound: b \ a ≤ b.
--
-- When a ≥ 0 (which the DUnit invariant guarantees), b − a ≤ b holds
-- trivially by arithmetic. This property makes that guarantee explicit
-- as a QuickCheck check, catching any future clamping or normalisation
-- that might violate it.
--
-- The ==> guard discards cases where a > b; we use fromMaybe True
-- (conservative pass on the unreachable Nothing branch).
prop_diff_upper_bound :: DUnit -> DUnit -> Property
prop_diff_upper_bound a b =
  a <= b ==>
    fromMaybe True $ do
      bma <- dDiff b a
      return (bma <= b)

-- | D-Poset law (iii), antitone part:
-- if a ≤ b ≤ c then c \\ b ≤ c \\ a.
--
-- The triple (a, b, c) is generated by construction so the ordering
-- invariant a ≤ b ≤ c holds structurally.  We draw a from the standard
-- Arbitrary DUnit instance (n/1000 for n ∈ 0..1000), then pick exact
-- Rational deltas delta1, delta2 ∈ {0, 1/1000, …, k/1000} such that
-- a + delta1 + delta2 ≤ 1.  This eliminates the ==> guard entirely and
-- generates non-trivial triples in every case.
--
-- Nothing is unreachable given a ≤ b ≤ c: the property is stated without
-- fromMaybe masking to make any accidental Nothing a hard failure.
prop_diff_antitone :: Property
prop_diff_antitone = forAll gen $ \(a, b, c) ->
    case (dDiff c b, dDiff c a) of
      (Just cminb, Just cmina) -> cminb <= cmina
      _                        -> error "prop_diff_antitone: unreachable Nothing"
  where
    gen :: Gen (DUnit, DUnit, DUnit)
    gen = do
      -- a = na/1000, na ∈ [0, 1000]
      na     <- chooseInt (0, 1000)
      -- delta1 = nd1/1000, delta2 = nd2/1000 with na + nd1 + nd2 ≤ 1000
      nd1    <- chooseInt (0, 1000 - na)
      nd2    <- chooseInt (0, 1000 - na - nd1)
      let a = DUnit (fromIntegral na  % 1000)
          b = DUnit (fromIntegral (na + nd1) % 1000)
          c = DUnit (fromIntegral (na + nd1 + nd2) % 1000)
      return (a, b, c)

-- | D-Poset law (ii): b \\ (b \\ a) = a  (exact equality).
--
-- Under Rational arithmetic, b - (b - a) = a is a ring identity — no
-- tolerance is needed or appropriate.  The ==> guard ensures a ≤ b;
-- the property is stated without fromMaybe so a spurious Nothing is
-- a hard failure rather than a silent pass.
prop_diff_involution :: DUnit -> DUnit -> Property
prop_diff_involution a b =
  a <= b ==>
    case dDiff b a of
      Nothing  -> error "prop_diff_involution: dDiff undefined despite a <= b"
      Just bma ->
        case dDiff b bma of
          Nothing   -> error "prop_diff_involution: second dDiff undefined"
          Just back -> back == a
